### PR TITLE
.NET9 support

### PR DESCRIPTION
**Pull request by molinch**
@mariusGundersen Here I tackled the changes I listed on https://github.com/ClaveConsulting/Expressionify/issues/30

If we could have a prerelease nuget I could play with it

### CODE REVIEW

**Comment by mariusGundersen** [comment]
Make sure you clone with all the tags and the pre release will get the right version number

**Comment by molinch** [comment]
@mariusGundersen I'm sorry I don't understand what's needed, I have all tags locally
Could you explain the process more?

**Comment by mariusGundersen** [comment]
I'm not entirely sure, to be honest. This pr gets the wrong version number, but I don't know why. It should look at previous tags in order to find the next one, but it's not working. I made a small change, maybe you can try rebasing or pushing a trivial change so it will build again?

I'm on holiday until the new year so I have limited resources to figure this out.

**Comment by molinch** [comment]
@mariusGundersen  It's so weird, with the extra commit somehow now the version number is fine now.
However, I don't think 6.7.2 makes sense since 7.0.0 was already published on nuget.org.
IMO we should go for 9.0.0 to be aligned with EF9. I'm not sure how to do that, I guess we would need to create a tag.

**Comment by mariusGundersen** [comment]
One of the commits needs to be marked as breaking to force a major version bump. But since it's multiple I guess I'll have to do something manually

**Comment by molinch** [comment]
@mariusGundersen I had to bring back ParameterExtractingExpressionVisitor from EF8 as the funcletizer behaves differently (it will trigger an access of the parameter values, which ends as throwing since we guard against it).

I tested all changes against our massive solution, we heavily use Expressionify, and it works as a charm.

Do you think we could have a prerelease package somehow on nuget?

**Comment by mariusGundersen** [comment]
Yes, just add BREAKING CHANGES to one of the commits so it will bump it up to a major version change. I can then publish the pre-release package

**Comment by molinch** [comment]
@mariusGundersen That's done.

**Comment by mariusGundersen** [comment]
I've created a prerelease, and I've made a v8.0.0 tag, so the next one is v9.0.0. You can rebase on top of master to see this

**Comment by molinch** [comment]
@mariusGundersen Thanks! it's now displaying the proper version 9.0.0

**Comment by mariusGundersen** [comment]
Please give the pre-release a test and let me know if it's working correctly

**Comment by molinch** [comment]
@mariusGundersen It's not working at all with the prerelease so I decompiled it, to see what's there, and none of my changes are inside. It's built from your master, not my PR.

**Comment by molinch** [comment]
Just so you believe me :)

For example, here:
image

It is missing:
```csharp
public Expression<Func<QueryContext, TResult>> PrecompileQuery<TResult>(Expression query, bool async) => _decoratedCompiler.PrecompileQuery<TResult>(query, async);
```

**Comment by mariusGundersen** [comment]
I believe you! Using the pull_request_target github action is required for security but is really difficult to do correctly. Can you rebase (please rebase, don't merge) on master again and see if that helps?

**Comment by molinch** [comment]
@mariusGundersen I think it won't fly as it uses the pipeline from your master, while I did pipeline changes to use .NET9 ... 
We have a chicken/egg issue here.

**Comment by mariusGundersen** [comment]
Yup, this is fun, isn't it...

**Comment by mariusGundersen** [comment]
Let's try one more rebase

**Comment by molinch** [comment]
@mariusGundersen Alleluia! let's try another prerelease :)

**Comment by molinch** [comment]
@mariusGundersen  It works as a charm now :)

**Pull request merged**
